name: Build and deploy JAR app to Azure Web App - EcoSoftware-spring-boot

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install -DskipTests        
        working-directory: Scrum6/Scrum6

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: Scrum6/Scrum6/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C855CF92BA3147BB94BAD88A6B766221 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_176CC9D528A34E4F868A5F4339CF3AAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17123F0CBDE448348E1265898989836D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: EcoSoftware-spring-boot
          package: '*.jar'
